### ISSUE TITLE
Chisel/Verilator test failing

### ISSUE THREAD

**Issue by daniel-k** [ekiwi/pynq#1]
I'm currently doing the system setup on my Archlinux machine. I have chisel, sbt and verilator installed, but the second test is failing. I cannot judge if this is due to the version of my tools or maybe just a minor bug, so here's the log:

```
verilated.o: In function `VL_FINISH_MT(char const*, int, char const*)':
verilated.cpp:(.text+0x7): undefined reference to `vl_finish(char const*, int, char const*)'
collect2: error: ld returned 1 exit status
make: Leaving directory '/home/daniel/Entwicklung/pynq/chisel/test_run_dir/pynq.GCDTester1346527907'
[info] GCDTester:
[info] Queue
[info] - should behave like a bounded queue (with firrtl)
[info] Queue
[info] - should behave like a bounded queue (with verilator) *** FAILED ***
[info]   java.lang.IllegalArgumentException: requirement failed: test_run_dir/pynq.GCDTester1346527907/VQueue doesn't exist
[info]   at scala.Predef$.require(Predef.scala:277)
[info]   at chisel3.iotesters.TesterProcess$.apply(PeekPokeTesterUtils.scala:153)
[info]   at chisel3.iotesters.SimApiInterface.<init>(SimApiInterface.scala:36)
[info]   at chisel3.iotesters.VerilatorBackend.<init>(VerilatorBackend.scala:281)
[info]   at chisel3.iotesters.setupVerilatorBackend$.apply(VerilatorBackend.scala:270)
[info]   at chisel3.iotesters.Driver$.$anonfun$execute$2(Driver.scala:53)
[info]   at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:12)
[info]   at logger.Logger$.$anonfun$makeScope$2(Logger.scala:129)
[info]   at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
[info]   at logger.Logger$.makeScope(Logger.scala:127)
[info]   ...
[info] ScalaTest
[info] Run completed in 5 seconds, 731 milliseconds.
[info] Total number of tests run: 2
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed: Total 2, Failed 1, Errors 0, Passed 1
[error] Failed tests:
[error] 	pynq.GCDTester
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 62 s, completed Jan 2, 2018 3:09:31 PM
```

**Comment by daniel-k** [comment]
Looks like this is an upstream chisel issue (https://github.com/ucb-bar/chisel-tutorial/issues/111). Will look into it

**Comment by daniel-k** [comment]
Solved it by using verilator 3.904 as recommended in the upstream issue. If any Arch user needs help, just reopen this issue :)

**Comment by ekiwi** [comment]
Ah ok. So your `verilator` version can also be too new... oh well

**Comment by medabme** [comment]
I have a problem with my test code. I've Verilator 4.011 already  installed.
This is a part of code :
`  "should work with verilator" in {
      iotesters.Driver.execute(
        args = Array("--backend-name", "verilator", "--target-dir", targetDirName, "--top-name", "complex_mem_test"),
        dut = () => new ComplexMemory(memoryDepth = 65536)
      ) { c => new ComplexMemoryTester(c)
      } should be(true)
    }
  }
`
This is the error:
` should work with verilator *** FAILED ***
[info]   chisel3.iotesters.TestApplicationException: test application exit - exit code 134
[info]   at chisel3.iotesters.SimApiInterface.throwExceptionIfDead(SimApiInterface.scala:98)
[info]   at chisel3.iotesters.SimApiInterface.chisel3$iotesters$SimApiInterface$$mwhile(SimApiInterface.scala:107)
[info]   at chisel3.iotesters.SimApiInterface$$anonfun$start$3.apply$mcVI$sp(SimApiInterface.scala:268)
[info]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
[info]   at chisel3.iotesters.SimApiInterface.start(SimApiInterface.scala:266)
[info]   at chisel3.iotesters.SimApiInterface.<init>(SimApiInterface.scala:325)
[info]   at chisel3.iotesters.VerilatorBackend.<init>(VerilatorBackend.scala:295)
[info]   at chisel3.iotesters.setupVerilatorBackend$.apply(VerilatorBackend.scala:284)
[info]   at chisel3.iotesters.Driver$$anonfun$execute$1$$anonfun$apply$mcZ$sp$1.apply$mcZ$sp(Driver.scala:56)
[info]   at chisel3.iotesters.Driver$$anonfun$execute$1$$anonfun$apply$mcZ$sp$1.apply(Driver.scala:39)
[info]   ...
[info] ScalaTest
[info] Run completed in 1 minute, 1 second.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed: Total 1, Failed 1, Errors 0, Passed 0
[error] Failed tests:
[error] 	util.GaussianBlurSpec
[error] (Test / testOnly) sbt.TestsFailedException: Tests unsuccessful`

**Comment by ekiwi** [comment]
Can you please post the complete output? There might be some output from the verilator compilation earlier in the output.

**Comment by medabme** [comment]
Here is the complete output.
`[info] [0.018] Elaborating design...
[info] [0.731] Done elaborating.
Total FIRRTL Compile Time: 1977.1 ms
cd /home/med/workspace/ChiselProjects/convolution/test_run_dir/complex_mem_test && verilator --cc ComplexMemory.v --assert -Wno-fatal -Wno-WIDTH -Wno-STMTDLY -O1 --top-module ComplexMemory +define+TOP_TYPE=VComplexMemory +define+PRINTF_COND=!ComplexMemory.reset +define+STOP_COND=!ComplexMemory.reset -CFLAGS "-Wno-undefined-bool-conversion -O1 -DTOP_TYPE=VComplexMemory -DVL_USER_FINISH -include VComplexMemory.h" -Mdir /home/med/workspace/ChiselProjects/convolution/test_run_dir/complex_mem_test -f /home/med/workspace/ChiselProjects/convolution/test_run_dir/complex_mem_test/firrtl_black_box_resource_files.f --exe /home/med/workspace/ChiselProjects/convolution/test_run_dir/complex_mem_test/ComplexMemory-harness.cpp --trace
make: Entering directory '/home/med/workspace/ChiselProjects/convolution/test_run_dir/complex_mem_test'
g++  -I.  -MMD -I/usr/local/share/verilator/include -I/usr/local/share/verilator/include/vltstd -DVL_PRINTF=printf -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -Wno-bool-operation -Wno-sign-compare -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -Wno-undefined-bool-conversion -O1 -DTOP_TYPE=VComplexMemory -DVL_USER_FINISH -include VComplexMemory.h   -c -o ComplexMemory-harness.o /home/med/workspace/ChiselProjects/convolution/test_run_dir/complex_mem_test/ComplexMemory-harness.cpp
g++  -I.  -MMD -I/usr/local/share/verilator/include -I/usr/local/share/verilator/include/vltstd -DVL_PRINTF=printf -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -Wno-bool-operation -Wno-sign-compare -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -Wno-undefined-bool-conversion -O1 -DTOP_TYPE=VComplexMemory -DVL_USER_FINISH -include VComplexMemory.h   -c -o verilated.o /usr/local/share/verilator/include/verilated.cpp
g++  -I.  -MMD -I/usr/local/share/verilator/include -I/usr/local/share/verilator/include/vltstd -DVL_PRINTF=printf -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -Wno-bool-operation -Wno-sign-compare -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -Wno-undefined-bool-conversion -O1 -DTOP_TYPE=VComplexMemory -DVL_USER_FINISH -include VComplexMemory.h   -c -o verilated_vcd_c.o /usr/local/share/verilator/include/verilated_vcd_c.cpp
/usr/bin/perl /usr/local/share/verilator/bin/verilator_includer -DVL_INCLUDE_OPT=include VComplexMemory.cpp VComplexMemory___024unit.cpp > VComplexMemory__ALLcls.cpp
/usr/bin/perl /usr/local/share/verilator/bin/verilator_includer -DVL_INCLUDE_OPT=include VComplexMemory__Trace.cpp VComplexMemory__Syms.cpp VComplexMemory__Trace__Slow.cpp > VComplexMemory__ALLsup.cpp
g++  -I.  -MMD -I/usr/local/share/verilator/include -I/usr/local/share/verilator/include/vltstd -DVL_PRINTF=printf -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -Wno-bool-operation -Wno-sign-compare -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -Wno-undefined-bool-conversion -O1 -DTOP_TYPE=VComplexMemory -DVL_USER_FINISH -include VComplexMemory.h   -c -o VComplexMemory__ALLsup.o VComplexMemory__ALLsup.cpp
g++  -I.  -MMD -I/usr/local/share/verilator/include -I/usr/local/share/verilator/include/vltstd -DVL_PRINTF=printf -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -Wno-bool-operation -Wno-sign-compare -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -Wno-undefined-bool-conversion -O1 -DTOP_TYPE=VComplexMemory -DVL_USER_FINISH -include VComplexMemory.h   -c -o VComplexMemory__ALLcls.o VComplexMemory__ALLcls.cpp
      Archiving VComplexMemory__ALL.a ...
ar r VComplexMemory__ALL.a VComplexMemory__ALLcls.o VComplexMemory__ALLsup.o
ranlib VComplexMemory__ALL.a
g++    ComplexMemory-harness.o verilated.o verilated_vcd_c.o VComplexMemory__ALL.a    -o VComplexMemory -lm -lstdc++ 
make: Leaving directory '/home/med/workspace/ChiselProjects/convolution/test_run_dir/complex_mem_test'
sim start on Dell at Fri Sep 27 10:20:01 2019
inChannelName: 00004200.in
outChannelName: 00004200.out
cmdChannelName: 00004200.cmd
STARTING test_run_dir/complex_mem_test/VComplexMemory
Enabling waves..%Error: /resources/cameraman_a.bin:0: $readmem file not found
Aborting...
[info] GaussianBlurSpec:
[info] memory loading should be possible with complex memories
[info] - should work with verilator *** FAILED ***
[info]   chisel3.iotesters.TestApplicationException: test application exit - exit code 134
[info]   at chisel3.iotesters.SimApiInterface.throwExceptionIfDead(SimApiInterface.scala:98)
[info]   at chisel3.iotesters.SimApiInterface.chisel3$iotesters$SimApiInterface$$mwhile(SimApiInterface.scala:107)
[info]   at chisel3.iotesters.SimApiInterface$$anonfun$start$3.apply$mcVI$sp(SimApiInterface.scala:268)
[info]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
[info]   at chisel3.iotesters.SimApiInterface.start(SimApiInterface.scala:266)
[info]   at chisel3.iotesters.SimApiInterface.<init>(SimApiInterface.scala:325)
[info]   at chisel3.iotesters.VerilatorBackend.<init>(VerilatorBackend.scala:295)
[info]   at chisel3.iotesters.setupVerilatorBackend$.apply(VerilatorBackend.scala:284)
[info]   at chisel3.iotesters.Driver$$anonfun$execute$1$$anonfun$apply$mcZ$sp$1.apply$mcZ$sp(Driver.scala:56)
[info]   at chisel3.iotesters.Driver$$anonfun$execute$1$$anonfun$apply$mcZ$sp$1.apply(Driver.scala:39)
[info]   ...
[info] ScalaTest
[info] Run completed in 46 seconds, 822 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed: Total 1, Failed 1, Errors 0, Passed 0
[error] Failed tests:
[error] 	util.GaussianBlurSpec
[error] (Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 60 s, completed Sep 27, 2019 10:20:19 AM`

**Comment by ekiwi** [comment]
The problem here seems to be the following line:
```
%Error: /resources/cameraman_a.bin:0: $readmem file not found Aborting..
```

There seems to be a problem with memory initialization.

Is this a custom Chisel project? I don't rememberusing any memories for `pynq`.
If this is custom Chisel code, it is probably best to file a bug with the Chisel project: https://github.com/freechipsproject/chisel3

If you can post the source code of your design (or even better: a simplified version that exhibits the same failure) people will be able to help you quickly.

Thanks!

**Comment by medabme** [comment]
Yes it is a custom Chisel project using the memory test program from [https://github.com/freechipsproject/chisel-testers/blob/master/src/test/scala/examples/ComplexMemoryLoadingSpec.scala](url).
I posted my error here because i found similar issues (with verilator) so i thought that i can find some help.

Thanks for help!

**Comment by ekiwi** [comment]
> I posted my error here because i found similar issues (with verilator) so i thought that i can find some help.

Filing an issue with the `chisel-testers` project will give it a lot more visibility and get the people involved who are maintaining that part of Chisel. Good luck!
